services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk21
    privileged: true
    restart: unless-stopped
    user: root
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
volumes:
  jenkins_data:
