version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.4-alpine
#    restart: always
    environment:
      - POSTGRES_DB=book_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5423:5432'
    networks:
      - backend
networks:
  backend:
    driver: bridge
    name: backend

#    volumes:
#      - db:/var/lib/postgresql/data

#  jenkins:
#    container_name: jenkins
#    image: jenkins/jenkins:lts-jdk11
#    privileged: true
#    user: root
#    ports:
#      - '8081:8080'
#      - '50000:50000'
#    volumes:
#      - ~/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/local/bin/docker:/usr/local/bin/docker