version: '3.8'
services:
  db:
    container_name: postgres_container
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

#    volumes:
#      - db:/var/lib/postgresql/data
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: postgres
#    ports:
#      - '5050:80'
#  jenkins:
#    container_name: jenkins_container
#    image: jenkins/jenkins:lts-jdk11
#    privileged: true
#    user: root
#    ports:
#      - '8081:8080'
#      - '50000:50000'
#    volumes:
#      - ~/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/local/bin/docker:/usr/local/bin/docker